const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "94764609656"
const SESSION_ID = "PRABATH-MD~470TlLJK#B3fCqhGY8z3GAanuTl9pCpyai1FcrLyEnmwOIAoGk_E"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
